apiVersion: v1
kind: Service
metadata:
  name: azureadtokenapi
  labels:
    app: azureadtokenapi
    service: azureadtokenapi
spec:
  ports:
  - port: 80
    name: http
  type: ClusterIP
  selector:
    app: azureadtokenapi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azureadtokenapi-details
  labels:
    account: azureadtokenapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureadtokenapi-v1
  labels:
    app: azureadtokenapi
    version: v1
    aadpodidbinding: #{azureIdentity}# 
spec:
  replicas: #{replicas}#
  selector:
    matchLabels:
      app: azureadtokenapi
      version: v1
  template:
    metadata:
      labels:
        app: azureadtokenapi
        version: v1
        aadpodidbinding: #{azureIdentity}#
    spec:
      nodeSelector:
        #"beta.kubernetes.io/os": windows
        diapps: #{diappname}#
      serviceAccountName: azureadtokenapi-details
      containers:
      - name: azureadtokenapi
        image: #{ACRRepoImageName}#
        ports:
        - containerPort: 80             
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: #{APIEnvironment}#
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: azureadtokenapi-virtualservice 
spec:
  hosts:
  - "*"
  gateways:
  - #{VSGateway}#
  http:
  - match:
    - uri:
        prefix: /api/AzureADAuth/v1
    route:
    - destination:
        host: azureadtokenapi  
        port:
          number: 80